- name: Install Mysql Client
  ansible.builtin.yum:
    name: mysql
    status: installed

- name: Load Schema
  ansible.builtin.shell: mysql -h mysql-dev.devops-tools.online -uroot -pRootShop@1 </app/schema/"{{ component }}".sql
